export const ROUTES = {
  HOME: "/",
  ADMIN: "/admin",
  DASHBOARD: "/dashboard",
  LOGIN: "/login",
  REGISTER: "/register",
  NOTFOUND: "/*",
  DEALERS: "dealers",
  CUSTOMERS: "customers",
  TESTDRIVE: "testdrive",
  PROFILE: "profile",
  PROFILE_INFO: "profile/info",
  PROFILE_CHANGE: "profile/changeInfo",
  PROFILE_RESET: "profile/resetpassword",
  PROFILE_SCHEDULE: "profile/viewSchedule",
};
